### ISSUE TITLE
`Locale.lua:1753: table index is nil` (and possibly others)

### ISSUE THREAD

**Issue by tflo** [glassleo/Paragon#8] opened 2023-09-27 12:15 UTC
Getting more or less regularly errors with Paragon. Until now, I haven't observed them closely; will do so in the future to find out which error occurs when.

For now, this is one of them:

<details>
<summary><code>Paragon/Locale.lua:1753: table index is nil</code></summary>

```denizenscript
76x Paragon/Locale.lua:1753: table index is nil
[string "@Paragon/Locale.lua"]:1753: in function <Paragon/Locale.lua:1751>
[string "@Paragon/Core.lua"]:392: in function <Paragon/Core.lua:380>
[string "@Paragon/Core.lua"]:654: in function <Paragon/Core.lua:609>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1519: in function `OnUpdate'
[string "@FrameXML/ContainerFrame.lua"]:1486: in function `OnEnter'
[string "@FrameXML/ContainerFrame.lua"]:1482: in function <FrameXML/ContainerFrame.lua:1481>

Locals:
self = <table> {
 cfgTooltipHeader = "Item Tooltips"
 cfgTooltipAltsEnabledShift = "Show Extended Highest Reputation When Holding |cff00ff00<Shift>|r"
 f soridormi = "Soridormi"
 cfgTooltipHideNeutral = "Exclude |cffffff00Neutral|r Characters from Character List"
 cfgHighestReputationLabel = "Character List"
 cfgTooltipFiltersLabel = "Filters"
 cfgTooltipAltsLimitShiftLabel = "When Holding |cff00ff00<Shift>|r"
 cfgTooltipAltsLimitLabel = "Characters Listed"
 faction_standing_paragon = "Paragon"
 cfgTooltipHideExalted = "Exclude |cff4cc2ffExalted|r Characters from Character List (Non-Paragon Reputations)"
 cfgDisplayRealmNames = "Display Realm Names"
 cfgTooltipAltsEnabledAlt = "Switch to Lowest Reputation When Holding |cff00ff00<Alt>|r"
 cfgTooltipAltsEnabled = "Show Highest Reputation"
 cfgTooltipSubtext = "Paragon can add additional information to tooltips for reputation related items."
 cfgFrameSubtext = "Paragon keeps track of reputation for all your characters.

Type |cff00ffff/par <faction>|r in chat to bring up an overview window for a specific reputation faction.


To delete stored data for a character, type |cff00ffff/par delete <name or name-realm>|r in chat."
 cfgShortRealmNames = "Abbreviate Realm Names Into Acronyms"
 cfgTooltipHideUnfriendly = "Exclude |cffee6622Unfriendly|r, |cffff0000Hostile|r and |cffcc2222Hated|r Characters from Character List"
 cfgTooltipPersonalEnabled = "Show Your Current Reputation"
}
key = nil
s = "#NOLOC#nil#"
(*temporary) = "nil"
(*temporary) = "#"
(*temporary) = "table index is nil"
L = <table> {
 faction_standing_unknown = "Unknown"
 faction_standing_revered = "Revered"
 faction_standing_trusted_bodyguard = "Trusted Bodyguard"
 f sha'leth = "Sha'leth"
 f iskaara tuskarr = "Iskaara Tuskarr"
 f the oracles = "The Oracles"
 faction_standing_undiscovered = "Undiscovered"
 f emperor shaohao = "Emperor Shaohao"
 f huojin pandaren = "Huojin Pandaren"
 f baradin's wardens = "Baradin's Wardens"
 f wintersaber trainers = "Wintersaber Trainers"
 f horde expedition = "Horde Expedition"
 f honor hold = "Honor Hold"
 /paragon help = "|cFF00FFFFParagon|r Usage:
|cff00ffff/paragon <faction>|r  List Highest Reputation for the specified faction in chat
|cff00ffff/paragon delete <name or name-realm>|r  Delete a character's data
|cff00ffff/paragon config|r  Open the Options Panel"
 f keeper raynae = "Keeper Raynae"
 f darkspear trolls = "Darkspear Trolls"
 f hand of the prophet = "Hand of the Prophet"
 faction_standing_expert = "Expert"
 f the enlightened = "The Enlightened"
 faction_standing_journeyman = "Journeyman"
 f the unshackled = "The Unshackled"
 f talon's vengeance = "Talon's Vengeance"
 faction_standing_friend = "Friend"
 hold shift for highest reputation = "<Hold Shift for Highest Reputation>"
 f the sons of hodir = "The Sons of Hodir"
 f hydraxian waterlords = "Hydraxian Waterlords"
 f the violet eye = "The Violet Eye"
 faction_standing_paragon = "Paragon"
 f stormpike guard = "Stormpike Guard"
 /paragon delete no argument = "|cFF00FFFFParagon|r: No character name specified."
 f sporeggar = "Sporeggar"
 f the undying army = "The Undying Army"
 f warsong outriders = "Warsong Outriders"
 cfgTooltipHideNeutral = "Exclude |cffffff00Neutral|r Characters from Character List"
 hold shift for more = "<Hold Shift for More>"
 faction_standing_honored = "Honored"
 faction_standing_curiosity = "Curiosity"
 f the kalu'ak = "The Kalu'ak"
 f avengers of hyjal = "Avengers of Hyjal"
 faction_standing_chrono-friend = "Chrono-Friend"
 f gina mudclaw = "Gina Mudclaw"
 faction_standing_exalted = "Exalted"
 faction_standing_helpful_friend = "Helpful Friend"
 f ramkahen = "Ramkahen"
 faction_standing_stranger = "Stranger"
 f the nightfallen = "The Nightfallen"
 f maruuk centaur = "Maruuk Centaur"
 faction_standing_whelpling = "Whelpling"
 f booty bay = "Booty Bay"
 f the ascended = "The Ascended"
 f alliance vanguard = "Alliance Vanguard"
 f therazane = "Therazane"
 f the hand of vengeance = "The Hand of Vengeance"
 f voldunai = "Voldunai"
 faction_standing_valued = "Valued"
 faction_standing_timehopper = 
```
</details>

**Comment by glassleo** [comment] 2023-09-27 13:24
Which item are you hovering over when you get this error?

**Comment by tflo** [comment] 2023-09-27 14:43
> Which item are you hovering over when you get this error?

Have to find that one out. But I don't think I was hovering over anything, unless I wasn't aware ofc.

From your pre-edit:

> Are you using any other addons that modify the tooltop?

Sure. Many.

> Are you still getting errors with no other addons enabled?

Not verified. And, since the errors are not exactly reproducible on demand, this would be a tough one because it would require me to run around for hours/days without any non-Blizz addons. Not exactly a good gaming experience ;)

But of course I will have an eye open to see if I can spot any dependencies/interferences with certain addons.

Additional info:

In the past (last weeks/months) Paragon threw an error (almost) each time when the status of a faction changed from max rep to paragon (eligible for chest). But I'm not sure if the reported error from above is the same, I tend to think this was a different one. As promised, I'll watch the things more closely in the next days.

**Comment by tflo** [comment] 2023-09-27 14:48
PS: Initial point of this issue report was to find out if you are actually (still) interested in fixing the addon. Now that that is clear, we can get to work :)

**Comment by tflo** [comment] 2023-09-27 14:58
here a list of my loaded addons with my Full set:

<details>
<summary>Details</summary>
DBM-Core, DBM-StatusBarTimers, DBM-Archaeology, DBM-SoundEventsPack, DBM-VPVEM, Accountant_Classic, ActionBarButtonGrowthDirection, AddonUsage, AdvancedInterfaceOptions, AllTheThings, Alts, AppearanceTooltip, Ara_Broker_XP, Armory, ArmoryGuildBank, Auctionator, AutoQuestTracker_MkIII, AutoConfirmEquip, BagSync, BankStack, BattlePetBattleUITweaks, BattlePetBreedID, Battle Pet Daily Tamer, BattlePetCount, Bazooka, Bazooka_Options, BelowAverageItems, BetterFishing, BetterWorldQuests, BlizzMove, Broker_Calendar, Broker_TSMProfile, Broker_Cash, Broker_WorldQuests, BrokerAnything, !BugGrabber, BugSack, ButtonForge, ButtonForge TFPlugin, BuyEmAll, CanIMogIt, ColorPickerPlus, CooldownToGo, CooldownToGo_Options, CopyAnything, DeathAlert, Details_CastLog, Details, Details_DeathGraphs, Details_Compare2, Details_EncounterDetails, Details_TimeLine, Details_TinyThreat, Details_ChartViewer, DragonRaceTimes, DropTheCheapestThing, DungeonHelper, EavesDrop, EditBox-Font-Improver, EmoteLDB, EnhancedRaidFrames, ErrorFilter, Executive_Assistant, ExtraQuestButton, FactionAddict, FavoriteContacts, !!!GarbageProtector, GTFO, GuildBankSnapshots, HandyNotes, HandyNotes_Dragonflight, HandyNotes_DragonflightTreasures, HandyNotes_TravelGuide, HandyNotes_LimitedSupplyVendors, HandyNotes_WorldMapButton, Hekili, ImprovedStableFrame, InFlight_Load, InstanceAchievementTracker, ItemVersion, KillTrack, Krowi_AchievementFilter, LargerMacroIconSelection, Leatrix_Maps, Leatrix_Plus, Ace3, LiteBag, LiteMount, LiteMount TF-Enhance, ls_Toasts, M6, MapLine, MasterPlanA, MerchantPlus, MiniMapLine, MobInfo2, MoveEmAll, MoveIt, SharedMedia_MyMedia, NoAutoClose, NPCTime, OmniCC, OPie, Paragon, Paste, PersistentWorldMap, tdBattlePetScript, PetWalker, !PileOfCode, PrettyReputation, Quartz, Quartz_School, Quester, QuestsChanged, Rarity, Rarity_Options, Recent, ReEnhancedStackSplit, Rematch, Rematch_TSMPetValues, !RequiresLevelX, SavedInstances, SellableItemDrops, ServerRestartSound, SexyReputation, SharedMedia, SharedMedia_NoAsianFonts, Sheepdog, SilverDragon, SilverDragon_Overlay, SilverDragon_RangeExtender, SimpleAddonManager, SimpleItemLevel, Simulationcraft, Stash, TaintLess, TalentLoadoutBroker, TalentLoadoutManager, TalentTreeTweaks, TalentTreeViewer_Loader, TidyPlates_ThreatPlates, TinyPad, TipTac, TipTacItemRef, TipTacTalents, TokenPrice, TomeOfTeleportation, TomTom, ToyBoxEnhanced, TradeSkillFluxCapacitor, TradeSkillMaster, TradeSkillMaster_AppHelper, UnlimitedMapPinDistance, Vendor, VenturePlan, VolumeTooltip, WarlockGrimoires, WeakAuras, WorldMapTrackingEnhanced, WIT, WorthIt-Guides, WoWthing_Collector, WQAchievements, xanAchievementMover, zifPet, ZonePetsList
[Total: 166]
</details>

But, I think (not 100% sure) I've seen it also happening with my Resting set:

<details>
<summary>Details</summary>
Accountant_Classic, ActionBarButtonGrowthDirection, AddonUsage, AdvancedInterfaceOptions, Alts, AppearanceTooltip, Armory, ArmoryGuildBank, Auctionator, AutoQuestTracker_MkIII, AutoConfirmEquip, BagSync, BankStack, BattlePetBreedID, BattlePetCount, Bazooka, Bazooka_Options, BlizzMove, Broker_Calendar, Broker_TSMProfile, Broker_Cash, BrokerAnything, !BugGrabber, BugSack, ButtonForge, ButtonForge TFPlugin, BuyEmAll, CanIMogIt, ColorPickerPlus, CopyAnything, EditBox-Font-Improver, EmoteLDB, Executive_Assistant, FactionAddict, FavoriteContacts, !!!GarbageProtector, GuildBankSnapshots, ImprovedStableFrame, ItemVersion, LargerMacroIconSelection, Leatrix_Plus, Ace3, LiteBag, LiteMount, LiteMount TF-Enhance, ls_Toasts, M6, MasterPlanA, MerchantPlus, MoveEmAll, MoveIt, SharedMedia_MyMedia, NoAutoClose, OPie, Paragon, Paste, tdBattlePetScript, PetWalker, !PileOfCode, PrettyReputation, Quester, QuestsChanged, Recent, ReEnhancedStackSplit, Rematch, Rematch_TSMPetValues, !RequiresLevelX, SavedInstances, ServerRestartSound, SexyReputation, SharedMedia, SharedMedia_NoAsianFonts, SimpleAddonManager, SimpleItemLevel, Stash, TaintLess, TinyPad, TipTac, TipTacItemRef, TipTacTalents, TokenPrice, TomeOfTeleportation, ToyBoxEnhanced, TradeSkillFluxCapacitor, TradeSkillMaster, TradeSkillMaster_AppHelper, Vendor, VenturePlan, VolumeTooltip, WarlockGrimoires, WeakAuras, WoWthing_Collector, WQAchievements, xanAchievementMover, zifPet
[Total: 95]
</details>

This is meant for you to skim through, maybe something calls your attention, in terms of possible conflicts.

**Comment by glassleo** [comment] 2023-09-27 18:21
I don't think another addon is interfering, which is why I edited my intial comment.

Are you using the latest version of Paragon?

It looks very similar to #5 but I am not able to reproduce the error on my end. It would help a lot if we knew which item causes the error.

**Comment by glassleo** [comment] 2023-09-27 18:28
Also could you attach your saved variables for Paragon?

It's a file called ``Paragon.lua`` located in your World of Warcraft folder > WTF > Account > (your account name) > SavedVariables

**Comment by tflo** [comment] 2023-09-27 18:31
> Are you using the latest version of the addon?

Well, there isn't a proper version string in the toc, at the time of writing I was using this:

<img width="698" alt="Screenshot 2023-09-27 at 20 25 52" src="https://github.com/glassleo/Paragon/assets/1410282/c920431d-5f47-4713-bd51-778a680ccb84">


 
Will upload the SV in 2 min.

**Comment by tflo** [comment] 2023-09-27 18:32
Here the SV file:

[Paragon.lua.zip](https://github.com/glassleo/Paragon/files/12742092/Paragon.lua.zip)

**Comment by glassleo** [comment] 2023-09-27 18:33
> Here the SV file:
> 
> [Paragon.lua.zip](https://github.com/glassleo/Paragon/files/12742092/Paragon.lua.zip)

Thanks! Do you remember which character you were on last time you received an error?

**Comment by tflo** [comment] 2023-09-27 18:39
I'm definitely getting this error on different chars (I have 17 maxLv chars + a couple more). If you are really asking me which char was associated with the error log posted above, sorry I can't remember (I'm 56 years old, in case this is an excuse ;)

But, next time I will remember :)

**Comment by glassleo** [comment] 2023-09-27 18:42
It was probably Soridormi related. I am able to reproduce the error with your SavedVariables now. Investigating.

**Comment by tflo** [comment] 2023-09-27 18:44
The `Paragon.lua` file I uploaded is not necessarily the one from the char it errored out. But, as said it is erroring out on more than 1 char.

**Comment by glassleo** [comment] 2023-09-27 18:45
Typing ``/par soridormi``gives you the error right? You were probably getting it when hovering over 1000 reputation item you get from the first Time Rift of the week as well.

**Comment by glassleo** [comment] 2023-09-27 18:46
Now I'm just trying to figure out why you are getting the error with your variables while I was not.

**Comment by tflo** [comment] 2023-09-27 18:48
Yep, `/par soridormi` gives me this:

<details>
<summary><code>Details</code></summary>

```denizenscript
1x Paragon/Locale.lua:1753: table index is nil
[string "@Paragon/Locale.lua"]:1753: in function <Paragon/Locale.lua:1751>
[string "@Paragon/Core.lua"]:392: in function <Paragon/Core.lua:380>
[string "@Paragon/Core.lua"]:505: in function <Paragon/Core.lua:438>
[string "@Paragon/Core.lua"]:739: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5281: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4938: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4974: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:141_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:141_OnEnterPressed"]:1>

Locals:
self = <table> {
 cfgTooltipHeader = "Item Tooltips"
 cfgTooltipAltsEnabledShift = "Show Extended Highest Reputation When Holding |cff00ff00<Shift>|r"
 f soridormi = "Soridormi"
 cfgTooltipHideNeutral = "Exclude |cffffff00Neutral|r Characters from Character List"
 cfgHighestReputationLabel = "Character List"
 cfgTooltipFiltersLabel = "Filters"
 cfgTooltipAltsLimitShiftLabel = "When Holding |cff00ff00<Shift>|r"
 cfgTooltipAltsLimitLabel = "Characters Listed"
 highest reputation = "Highest Reputation"
 faction_standing_paragon = "Paragon"
 cfgTooltipHideExalted = "Exclude |cff4cc2ffExalted|r Characters from Character List (Non-Paragon Reputations)"
 cfgDisplayRealmNames = "Display Realm Names"
 cfgTooltipAltsEnabledAlt = "Switch to Lowest Reputation When Holding |cff00ff00<Alt>|r"
 cfgTooltipAltsEnabled = "Show Highest Reputation"
 shorthands = <table> {
 }
 hold shift for more = "<Hold Shift for More>"
 cfgTooltipSubtext = "Paragon can add additional information to tooltips for reputation related items."
 f guild = "Guild"
 cfgFrameSubtext = "Paragon keeps track of reputation for all your characters.

Type |cff00ffff/par <faction>|r in chat to bring up an overview window for a specific reputation faction.


To delete stored data for a character, type |cff00ffff/par delete <name or name-realm>|r in chat."
 cfgShortRealmNames = "Abbreviate Realm Names Into Acronyms"
 cfgTooltipHideUnfriendly = "Exclude |cffee6622Unfriendly|r, |cffff0000Hostile|r and |cffcc2222Hated|r Characters from Character List"
 cfgTooltipPersonalEnabled = "Show Your Current Reputation"
}
key = nil
s = "#NOLOC#nil#"
(*temporary) = "nil"
(*temporary) = "#"
(*temporary) = "table index is nil"
L = <table> {
 faction_standing_unknown = "Unknown"
 faction_standing_revered = "Revered"
 faction_standing_trusted_bodyguard = "Trusted Bodyguard"
 f sha'leth = "Sha'leth"
 f iskaara tuskarr = "Iskaara Tuskarr"
 f the oracles = "The Oracles"
 faction_standing_undiscovered = "Undiscovered"
 f emperor shaohao = "Emperor Shaohao"
 f huojin pandaren = "Huojin Pandaren"
 f baradin's wardens = "Baradin's Wardens"
 f wintersaber trainers = "Wintersaber Trainers"
 f horde expedition = "Horde Expedition"
 f honor hold = "Honor Hold"
 /paragon help = "|cFF00FFFFParagon|r Usage:
|cff00ffff/paragon <faction>|r  List Highest Reputation for the specified faction in chat
|cff00ffff/paragon delete <name or name-realm>|r  Delete a character's data
|cff00ffff/paragon config|r  Open the Options Panel"
 f keeper raynae = "Keeper Raynae"
 f darkspear trolls = "Darkspear Trolls"
 f hand of the prophet = "Hand of the Prophet"
 faction_standing_expert = "Expert"
 f the enlightened = "The Enlightened"
 faction_standing_journeyman = "Journeyman"
 f the unshackled = "The Unshackled"
 f talon's vengeance = "Talon's Vengeance"
 faction_standing_friend = "Friend"
 hold shift for highest reputation = "<Hold Shift for Highest Reputation>"
 f the sons of hodir = "The Sons of Hodir"
 f hydraxian waterlords = "Hydraxian Waterlords"
 f the violet eye = "The Violet Eye"
 faction_standing_paragon = "Paragon"
 f stormpike guard = "Stormpike Guard"
 /paragon delete no argument = "|cFF00FFFFParagon|r: No character name specified."
 f sporeggar = "Sporeggar"
 f the undying army = "The Undying Army"
 f warsong outriders = "Warsong Outriders"
 cfgTooltipHideNeutral = "Exclude |cffffff00Neutral|r Characters from Character List"
 hold shift for more = "<Hold Shift for More>"
 faction_standing_honored = "Honored"
 faction_standing_curiosity = "Curiosity"
 f the kalu'ak = "The Kalu'ak"
 f avengers of hyjal = "Avengers of Hyjal"
 faction_standing_chrono-friend = "Chrono-Friend"
 f gina mudclaw = "Gina Mudclaw"
 faction_standing_exalted = "Exalted"
 faction_standing_helpful_friend = "Helpful Friend"
 f ramkahen = "Ramkahen"
 faction_standing_stranger = "Stranger"
 f the nightfallen = "The Nightfallen"
 f maruuk centaur = "Maruuk Centaur"
 faction_standing_whelpling = "Whelpling"
 f booty bay = "Booty Bay"
 f the ascended = "The Ascended"
 f alliance vanguard = "Alliance Vanguard"
 f therazane = "Therazane"
 f the 
```
</details>

**Comment by glassleo** [comment] 2023-09-27 19:04
I have found the issue. A few of your characters have incorrect save data for Soridormi from a previous version of Paragon where it wasn't being recorded properly and then you probably have not logged in to them since the bug was "fixed" meaning they never updated their saved data. They have a higher ``standingId``(6) than what is possible for Soridormi (5) and that is throwing an error.

I will work on a fix asap.

**Comment by tflo** [comment] 2023-09-27 19:09
> and then you probably have not logged in to them since the bug was "fixed" 

This is highly unlikely, unless the fix was in the last weeks or so.

**Comment by tflo** [comment] 2023-09-27 19:12
More precisely: On my main toons (where the error is thrown too), I'm logging in daily.

**Comment by glassleo** [comment] 2023-09-27 19:32
Could you try the following (in order):

1. Log in to Llynis then log out
2. Log in to Yago then log out
3. Log in to any other character and type ``/par soridormi``

Do you still get an error?

**Comment by tflo** [comment] 2023-09-27 19:39
OK, logging out of my current toon ('Rufie'), then doing as requested…

**Comment by tflo** [comment] 2023-09-27 19:40
…logged in with 'Llynis': no errors

**Comment by tflo** [comment] 2023-09-27 19:42
logged in with 'Yago': no errors

**Comment by tflo** [comment] 2023-09-27 19:46
logged in with another toon ('Lonk') and run `/par soridormi`:

<details>
<summary><code>Details</code></summary>

```denizenscript
2x Paragon/Locale.lua:1753: table index is nil
[string "@Paragon/Locale.lua"]:1753: in function <Paragon/Locale.lua:1751>
[string "@Paragon/Core.lua"]:392: in function <Paragon/Core.lua:380>
[string "@Paragon/Core.lua"]:505: in function <Paragon/Core.lua:438>
[string "@Paragon/Core.lua"]:739: in function `?'
[string "@FrameXML/ChatFrame.lua"]:5281: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4938: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4974: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:141_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:141_OnEnterPressed"]:1>

Locals:
self = <table> {
 cfgTooltipHeader = "Item Tooltips"
 cfgTooltipAltsEnabledShift = "Show Extended Highest Reputation When Holding |cff00ff00<Shift>|r"
 f soridormi = "Soridormi"
 cfgTooltipHideNeutral = "Exclude |cffffff00Neutral|r Characters from Character List"
 cfgHighestReputationLabel = "Character List"
 cfgTooltipFiltersLabel = "Filters"
 cfgTooltipAltsLimitShiftLabel = "When Holding |cff00ff00<Shift>|r"
 cfgTooltipAltsLimitLabel = "Characters Listed"
 highest reputation = "Highest Reputation"
 faction_standing_paragon = "Paragon"
 cfgTooltipHideExalted = "Exclude |cff4cc2ffExalted|r Characters from Character List (Non-Paragon Reputations)"
 cfgDisplayRealmNames = "Display Realm Names"
 cfgTooltipAltsEnabledAlt = "Switch to Lowest Reputation When Holding |cff00ff00<Alt>|r"
 cfgTooltipAltsEnabled = "Show Highest Reputation"
 shorthands = <table> {
 }
 hold shift for more = "<Hold Shift for More>"
 cfgTooltipSubtext = "Paragon can add additional information to tooltips for reputation related items."
 f guild = "Guild"
 cfgFrameSubtext = "Paragon keeps track of reputation for all your characters.

Type |cff00ffff/par <faction>|r in chat to bring up an overview window for a specific reputation faction.


To delete stored data for a character, type |cff00ffff/par delete <name or name-realm>|r in chat."
 cfgShortRealmNames = "Abbreviate Realm Names Into Acronyms"
 cfgTooltipHideUnfriendly = "Exclude |cffee6622Unfriendly|r, |cffff0000Hostile|r and |cffcc2222Hated|r Characters from Character List"
 cfgTooltipPersonalEnabled = "Show Your Current Reputation"
}
key = nil
s = "#NOLOC#nil#"
(*temporary) = "nil"
(*temporary) = "#"
(*temporary) = "table index is nil"
L = <table> {
 faction_standing_unknown = "Unknown"
 faction_standing_revered = "Revered"
 faction_standing_trusted_bodyguard = "Trusted Bodyguard"
 f sha'leth = "Sha'leth"
 f iskaara tuskarr = "Iskaara Tuskarr"
 f the oracles = "The Oracles"
 faction_standing_undiscovered = "Undiscovered"
 f emperor shaohao = "Emperor Shaohao"
 f huojin pandaren = "Huojin Pandaren"
 f baradin's wardens = "Baradin's Wardens"
 f wintersaber trainers = "Wintersaber Trainers"
 f horde expedition = "Horde Expedition"
 f honor hold = "Honor Hold"
 /paragon help = "|cFF00FFFFParagon|r Usage:
|cff00ffff/paragon <faction>|r  List Highest Reputation for the specified faction in chat
|cff00ffff/paragon delete <name or name-realm>|r  Delete a character's data
|cff00ffff/paragon config|r  Open the Options Panel"
 f keeper raynae = "Keeper Raynae"
 f darkspear trolls = "Darkspear Trolls"
 f hand of the prophet = "Hand of the Prophet"
 faction_standing_expert = "Expert"
 f the enlightened = "The Enlightened"
 faction_standing_journeyman = "Journeyman"
 f the unshackled = "The Unshackled"
 f talon's vengeance = "Talon's Vengeance"
 faction_standing_friend = "Friend"
 hold shift for highest reputation = "<Hold Shift for Highest Reputation>"
 f the sons of hodir = "The Sons of Hodir"
 f hydraxian waterlords = "Hydraxian Waterlords"
 f the violet eye = "The Violet Eye"
 faction_standing_paragon = "Paragon"
 f stormpike guard = "Stormpike Guard"
 /paragon delete no argument = "|cFF00FFFFParagon|r: No character name specified."
 f sporeggar = "Sporeggar"
 f the undying army = "The Undying Army"
 f warsong outriders = "Warsong Outriders"
 cfgTooltipHideNeutral = "Exclude |cffffff00Neutral|r Characters from Character List"
 hold shift for more = "<Hold Shift for More>"
 faction_standing_honored = "Honored"
 faction_standing_curiosity = "Curiosity"
 f the kalu'ak = "The Kalu'ak"
 f avengers of hyjal = "Avengers of Hyjal"
 faction_standing_chrono-friend = "Chrono-Friend"
 f gina mudclaw = "Gina Mudclaw"
 faction_standing_exalted = "Exalted"
 faction_standing_helpful_friend = "Helpful Friend"
 f ramkahen = "Ramkahen"
 faction_standing_stranger = "Stranger"
 f the nightfallen = "The Nightfallen"
 f maruuk centaur = "Maruuk Centaur"
 faction_standing_whelpling = "Whelpling"
 f booty bay = "Booty Bay"
 f the ascended = "The Ascended"
 f alliance vanguard = "Alliance Vanguard"
 f therazane = "Therazane"
 f the 
```
</details>

**Comment by tflo** [comment] 2023-09-27 19:53
just as an additional, potential, info:

True that the errors are frequent with Soridormi, but I'm almost 99% sure that I have seen them also with other reps, before Soridormi in its current form even existed.

**Comment by glassleo** [comment] 2023-09-27 20:00
I think I have fixed the bug.

Can you try this prerelease version of Paragon? You might have to log Llynis and Yago again to update their data for Soridormi after installing it. Either way it should no longer be throwing errors if there is invalid save data.

[Paragon.zip](https://github.com/glassleo/Paragon/files/12742872/Paragon.zip)

**Comment by tflo** [comment] 2023-09-27 20:13
OK, with your new version loaded, I did this:

- logged into Yago
- logged into Llyinis
- logged into a third toon (this time 'Osmadi')

run `/par Soridormi` while on the third toon: no errors :)

The return was this:

![WoWScrnShot_092723_220602](https://github.com/glassleo/Paragon/assets/1410282/9c053c34-c389-489a-b64f-140eef8ecb1f)

…which is not accurate (eg, Llynis and at least one other have max rep with Sori), but at leat it does not bug out :)

**Comment by tflo** [comment] 2023-09-27 20:17
So, I guess it'll be fine after one more run on each toon's DB.

**Comment by glassleo** [comment] 2023-09-27 20:18
Hmm that is strange. I manually set one of my characters to the same data as yours and mine updated.

What happens if you log in to Llynis and type ``/par soridormi``? Is it still marked as out of date for Llynis?

**Comment by tflo** [comment] 2023-09-27 20:22
Yes, it is. just tried that, bc I wanted to see if i were right with "So, I guess it'll be fine after one more run on each toon's DB."

But it doesn't seem so.

![WoWScrnShot_092723_221948](https://github.com/glassleo/Paragon/assets/1410282/ab5221f6-3fde-4e55-84e0-7e67d0080c80)

**Comment by tflo** [comment] 2023-09-27 20:25
Give me a sec, Ill reload on llynis and yago without any other addons…

**Comment by glassleo** [comment] 2023-09-27 20:26
Can you paste this in chat on either Yago or Llynis and give me the chat output?

``/dump C_GossipInfo.GetFriendshipReputation(2553)``

**Comment by tflo** [comment] 2023-09-27 20:32
quoting myself:

> Give me a sec, Ill reload on llynis and yago without any other addons…

This didn't change anything.

> Can you paste this

The output is (on Llynis):

```lua
Dump: value=C_GossipInfo.GetFriendshipReputation(2553)
[1]={
  maxRep=42000,
  text="Soridormi considers you |5Legend.",
  reversedColor=false,
  name="Soridormi",
  standing=42000,
  reactionThreshold=42000,
  reaction="Legend",
  friendshipFactionID=2553,
  texture=604882
}
```

**Comment by tflo** [comment] 2023-09-27 20:33
This toon (Llynis) indeed has max rep with the Rift Soridormi.

**Comment by glassleo** [comment] 2023-09-27 20:38
Ok, found the issue. I had completely missed to add the reputation thresholds for Soridormi.

Is it working if you try this version?
[Paragon.zip](https://github.com/glassleo/Paragon/files/12743146/Paragon.zip)

**Comment by glassleo** [comment] 2023-09-27 20:39
also that version has some debuf output in chat, just ignore it

**Comment by tflo** [comment] 2023-09-27 20:43
OK, seems correct now:

![WoWScrnShot_092723_224014](https://github.com/glassleo/Paragon/assets/1410282/da499349-0bf1-4040-be8c-6fd1acc36788)

Great! Although, as I said, I seem to remember seeing similar problems before 10.1.5. But, just let it go, I'll report when I get an error.

**Comment by glassleo** [comment] 2023-09-27 20:45
Sweet! Thank you so much for all the help debugging this. I'll push out the new version asap.

> Great! Although, as I said, I seem to remember seeing similar problems before 10.1.5. But, just let it go, I'll report when I get an error.

If there is invalid data it should at least not give any lua errors now.

**Comment by tflo** [comment] 2023-09-27 20:47
Thanks to you, and thanks for your time, I really appreciate addon authors who take care of their addons :) (They are like babies, aren't they? ;)

**Closed as completed** 2023-09-27 20:55 UTC
Labels: bug
